### ISSUE TITLE
Error message when launching this mod in a linux environment

### ISSUE THREAD

**Issue by Gecko483** [Sindusk/servertweaks#1]
File \src\main\java\mod\sin\server\tweaks\DeveloperCommands.java has an issue with line number 129 as follows:
classPool.appendClassPath("./mods/servertweaks/servertweaks.jar");
and throws error:
javassist.NotFoundException: ./mods/servertweaks/servertweaks.jar
	at javassist.JarClassPath.<init>(ClassPoolTail.java:152)
	at javassist.ClassPoolTail.makePathObject(ClassPoolTail.java:268)
	at javassist.ClassPoolTail.appendClassPath(ClassPoolTail.java:260)
	at javassist.ClassPool.appendClassPath(ClassPool.java:974)
	at mod.sin.servertweaks.DeveloperCommands.init(DeveloperCommands.java:129)
	at mod.sin.servertweaks.ServerTweaks.init(ServerTweaks.java:167)
	at org.gotti.wurmunlimited.modloader.ModLoaderShared.lambda$loadModsFromModDir$8(ModLoaderShared.java:174)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.gotti.wurmunlimited.modloader.ModLoaderShared.loadModsFromModDir(ModLoaderShared.java:172)
	at org.gotti.wurmunlimited.serverlauncher.DelegatedLauncher.main(DelegatedLauncher.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javassist.Loader.run(Loader.java:286)
	at org.gotti.wurmunlimited.serverlauncher.ServerLauncher.main(ServerLauncher.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at PatchedLauncher.main(PatchedLauncher.java:20)

Should be modified to:
classPool.appendClassPath("./mods/ServerTweaks/ServerTweaks.jar");

The reason for this is that everything in Linux is case sensitive, the work around is to create a duplicate file in the system at that aforementioned location with the different case ( all lowercase)

**Comment by Sindusk** [comment]
Issue should be resolved with latest commit. Thanks for tracking down the problem.
